config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '男の子' },
    { id: 3, name: '女の子' },
    { id: 4, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :tweets

end

app/models/pet_type.rb
class PetType < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' }, { id: 2, name: '犬' }, { id: 3, name: '猫' },
    { id: 4, name: 'ハムスター' }, { id: 5, name: 'ウサギ' }, { id: 6, name: 'フェレット' },
    { id: 7, name: 'カメ' }, { id: 8, name: '熱帯魚' }, { id: 9, name: 'トカゲ' },
    { id: 10, name: 'モルモット・チンチラ' }, { id: 11, name: 'インコ・オウム' }, { id: 12, name: 'ハリネズミ・テンレック' },
    { id: 13, name: 'リス・ジリス' }, { id: 14, name: 'ウーパールーパー' }, { id: 15, name: 'フクロウ・ミミズク' },
    { id: 16, name: 'モモンガ' }, { id: 17, name: 'サル' }, { id: 18, name: 'クモ' },
    { id: 19, name: 'マウス・デグー・ヤマネ' }, { id: 20, name: 'カエル' }, { id: 21, name: 'ザリガニ' },
    { id: 22, name: 'ヤドカリ' }, { id: 23, name: 'サソリ' }, { id: 24, name: 'イモリ・サンショウウオ' },
    { id: 25, name: '昆虫' }, { id: 26, name: 'デグー' }, { id: 27, name: 'ミーアキャット' },
    { id: 28, name: 'ミニブタ' }, { id: 29, name: '金魚' }, { id: 30, name: 'メダカ' },
    { id: 31, name: 'その他の鳥' }, { id: 32, name: 'その他の小動物' }, { id: 33, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :tweets

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :age, format: { with: /^[0-9]+$/ }
  validates :gender_id, numericality: { other_than: 1 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :pet_type
  belongs_to :gender

  with_options presence: true do
    validates :text
    validates :image
    validates :pet_type_id, numericality: { other_than: 1 }
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :likes
  has_many :comments

  validates :accountname, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:accountname])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.order('created_at DESC')
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uchinokogram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <p>
    Copyright Uchinokogram 2021.
  </p>
</footer>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("logo.png", class:"uhinoko-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag"search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-right1'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
    </ul>
    <ul class='lists-right2'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.accountname, "#", class: "user-accountname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second_header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", class:"second-logo"), "/" %>
</header>

app/views/tweets/index.html.erb
<%# ヘッダー %>
<%= render "shared/header"%>

<div class='main'>

<%# 画面上部の帯部分 %>
<%= image_tag "FotoJet.jpg", class:"top-image" %>

<%# 新着投稿 %>
  <div class='tweet-contents'>
    <h2 class='title'>New Tweet</h2>
    <ul class='tweet-lists'>

      <% @tweets.each do |tweet| %>
      <li class='list'>
        <%= link_to tweet_path(tweet.id) do %>
        <div class='tweet-img-content'>
          <%= tweet_tag tweet.image, class: "tweet-img" %>
        </div>
        <div class='tweet-info'>
          <div class='tweet-user'>
            <span><%= tweet.account.name %></span>
            <div class='heart-btn'>
              <%= image_tag "heart.png", class:"heart-icon" %>
              <span class='heart-count'>0</span>
            </div>
          </div>
        <% end %>
        </div>
      </li>
      <% end %>
   </ul>
  </div>
</div>

<%# 人気投稿順 %>

<%# フッター %>
<%= render "shared/footer"%>